owner: worldofplayers
repo: status
user-agent: worldofplayers

sites:
  - name: Forum
    url: https://forum.worldofplayers.de/forum/
  - name: Portalseite
    url: https://www.worldofplayers.de/
  - name: World of Gothic
    url: https://www.worldofgothic.de/
  - name: The Witcher
    url: https://www.the-witcher.de/

assignees:
  - mrgrain

status-website:
  theme: dark
  cname: staus.worldofplayers.de
  # baseUrl: /your-repo-name
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: WoP Status
  introTitle: "**World of Players Status**"
  introMessage: Zeigt an ob dein Lieblings-Forum gerade funktioniert oder nicht.
  navbar:
    - title: Status
      href: /
    - title: Infoforum
      href: https://forum.worldofplayers.de/forum/forums/146-Infoforum
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
